language: node_js
notifications:
  email: false
node_js:
  - "7"
  - "6"
dist: trusty
sudo: required
addons:
  sonarqube:
    organization: "$SONAR_ORGANIZATION"
    token:
      secure: "$SONAR_TOKEN"
    github_token:
      secure: "$GITHUB_ACCESS_TOKEN"
    branches:
      - master
      - develop
      - /[feat|fix|perf|docs|chore|style|refactor|test|revert].*/
jdk:
  - oraclejdk8
before_script:
  - npm prune
  - npm i -g jsdoc-to-markdown
after_success:
  - npm run semantic-release
script:
  - npm test
  # - sonar-scanner -X
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache:
  directories:
    - '$HOME/.sonar/cache'
    - node_modules
