sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 8
  - 7
  - 6
before_script:
  - npm prune
  - npm i -g jsdoc-to-markdown
after_success:
  - npm run semantic-release
script:
  - npm test
  - cat coverage/lcov.info | node_modules/.bin/coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
