---
addons:
  sonarcloud:
    organization:   "$SONAR_ORGANIZATION"
    token:
      secure:       "$SONAR_TOKEN"
    github_token:
      secure:       "$GH_TOKEN"
    branches:
      - master
      - /[build|chore|ci|docs|feat|fix|perf|refactor|revert|spike|style|test].*/
jdk:
  - oraclejdk8

os:
  - linux
  - osx

language: node_js

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.npm'

notifications:
  email: false

node_js:
  - '9'
  - '8'
  - '6'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_script:
  - npm prune
  - npm dedupe

script:
  - echo "$TRAVIS_PULL_REQUEST_BRANCH"
  - npm test

after_script:
  - cat docs/reports/coverage/lcov.info | npx coveralls
  # Send stats to SonarCloud for pull requests
  - test $TRAVIS_PULL_REQUEST != false
    && sonar-scanner -Dproject.settings=./sonar-project.properties -Dsonar.branch.name="$TRAVIS_PULL_REQUEST_BRANCH" -Dsonar.branch.target=master -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_TOKEN -X

jobs:
  include:
    - stage: release
      deploy:
        provider: npm
        skip_cleanup: true
        script:
          - npx travis-deploy-once "npx semantic-release"
